// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkecjtxqmnmyfnxpgmjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZWNqdHhxbW5teWZueHBnbWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDc4OTIsImV4cCI6MjA2ODMyMzg5Mn0.aaqkUSBsIteRjfpoxmaqSODFzPQdrj_bxOd0QJO8a3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});